server:
  listen:
    - 0.0.0.0@53
    - ::@53

log:
  - target: stdout
    any: info

database:
  storage: /var/lib/knot

template:
  - id: default
    storage: /var/lib/knot
    semantic-checks: on
    global-module: mod-dnstap/capture

mod-dnstap:
  - id: capture
    sink: unix:/dnstap/dnstap.sock

zone:
  - domain: agent.example.
    file: /etc/knot/zones/agent.example.zone
